### ISSUE TITLE
Video Reader performance and alternative considerations

### ISSUE THREAD

**Issue by Pedrexus** [NVIDIA/DALI#5173]
### Describe the question.

Dear all,

I have been working with a dataset with millions of videos lately and I wanted to improve the performance of my training pipeline. The problem is that I noticed that while using the video_resize reader, the gpu % and cpu % stays fairly low, around less than 10% (visualized with `nvtop`). 

I also noticed that for really large datasets, the build time increase, but I found my answer for that in https://github.com/NVIDIA/DALI/issues/4607.

In any case, I wanted to know how to work around this problem. I tried playing around with different parameters of the reader, but I saw no noticeable performance improvement (iterations/sec did not increase). 

Below, you can find my current configuration (hydra style):

```yaml
_target_: nvidia.dali.fn.readers.video_resize
_partial_: true
sequence_length: 8
additional_decode_surfaces: 2
antialias: true
channels: 3
dont_use_mmap: false
dtype: ${enum:nvidia.dali.types.DALIDataType.UINT8}
enable_frame_num: false
enable_timestamps: false
file_list_frame_num: false
file_list_include_preceding_frame: true
filenames:
labels:
device: gpu
initial_fill: 4096
lazy_init: false
image_type: ${enum:nvidia.dali.types.DALIImageType.RGB}
interp_type: ${enum:nvidia.dali.types.DALIInterpType.INTERP_LINEAR}
min_filter: ${enum:nvidia.dali.types.DALIInterpType.INTERP_LINEAR}
mag_filter: ${enum:nvidia.dali.types.DALIInterpType.INTERP_LINEAR}
max_size:
minibatch_size: 1024
mode: default
normalized: false
pad_last_batch: true
pad_sequences: false
prefetch_queue_depth: 4
preserve: false
random_shuffle: true
read_ahead: true
resize_x: 128
resize_y: 128
skip_vfr_check: true
stick_to_shard: true
stride: 4
```

I would like to know if there is a way to optimize the reader. I am actually considering converting the whole dataset to .npy files and using the numpy_reader instead, but given each video has different lengths, I am not sure how to get the same effect of `sequence_length` and `stride` yet.

I would be glad if you were able to provide me any help in understanding this problem and a possible work around.

Thank you again for the amazing library.

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report
